<?php
/**
 * BillingPostResponseBody
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pingram
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * BillingPostResponseBody Class Doc Comment
 *
 * @category Class
 * @description POST /billing response: organization usage limits + optional Checkout session.
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BillingPostResponseBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BillingPostResponseBody';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'organization_id' => 'string',
        'organization_type' => 'string',
        'creator' => 'string',
        'name' => 'string',
        'messages_cap' => 'float',
        'cost_cap' => 'float',
        'sms_cap' => 'float',
        'call_cap' => 'float',
        'billing_version' => 'float',
        'anniversary_date' => 'string',
        'allow_overage' => 'bool',
        'created_at' => 'string',
        'updated_at' => 'string',
        'session_id' => 'string',
        'url' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'organization_id' => null,
        'organization_type' => null,
        'creator' => null,
        'name' => null,
        'messages_cap' => null,
        'cost_cap' => null,
        'sms_cap' => null,
        'call_cap' => null,
        'billing_version' => null,
        'anniversary_date' => null,
        'allow_overage' => null,
        'created_at' => null,
        'updated_at' => null,
        'session_id' => null,
        'url' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'organization_id' => false,
        'organization_type' => false,
        'creator' => false,
        'name' => false,
        'messages_cap' => false,
        'cost_cap' => false,
        'sms_cap' => false,
        'call_cap' => false,
        'billing_version' => false,
        'anniversary_date' => false,
        'allow_overage' => false,
        'created_at' => false,
        'updated_at' => false,
        'session_id' => false,
        'url' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'organization_id' => 'organizationId',
        'organization_type' => 'organizationType',
        'creator' => 'creator',
        'name' => 'name',
        'messages_cap' => 'messagesCap',
        'cost_cap' => 'costCap',
        'sms_cap' => 'smsCap',
        'call_cap' => 'callCap',
        'billing_version' => 'billingVersion',
        'anniversary_date' => 'anniversaryDate',
        'allow_overage' => 'allowOverage',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'session_id' => 'sessionId',
        'url' => 'url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'organization_id' => 'setOrganizationId',
        'organization_type' => 'setOrganizationType',
        'creator' => 'setCreator',
        'name' => 'setName',
        'messages_cap' => 'setMessagesCap',
        'cost_cap' => 'setCostCap',
        'sms_cap' => 'setSmsCap',
        'call_cap' => 'setCallCap',
        'billing_version' => 'setBillingVersion',
        'anniversary_date' => 'setAnniversaryDate',
        'allow_overage' => 'setAllowOverage',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'session_id' => 'setSessionId',
        'url' => 'setUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'organization_id' => 'getOrganizationId',
        'organization_type' => 'getOrganizationType',
        'creator' => 'getCreator',
        'name' => 'getName',
        'messages_cap' => 'getMessagesCap',
        'cost_cap' => 'getCostCap',
        'sms_cap' => 'getSmsCap',
        'call_cap' => 'getCallCap',
        'billing_version' => 'getBillingVersion',
        'anniversary_date' => 'getAnniversaryDate',
        'allow_overage' => 'getAllowOverage',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'session_id' => 'getSessionId',
        'url' => 'getUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ORGANIZATION_TYPE_FREE = 'free';
    public const ORGANIZATION_TYPE_PAID = 'paid';
    public const BILLING_VERSION_NUMBER_1 = 1;
    public const BILLING_VERSION_NUMBER_3 = 3;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrganizationTypeAllowableValues()
    {
        return [
            self::ORGANIZATION_TYPE_FREE,
            self::ORGANIZATION_TYPE_PAID,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBillingVersionAllowableValues()
    {
        return [
            self::BILLING_VERSION_NUMBER_1,
            self::BILLING_VERSION_NUMBER_3,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('organization_type', $data ?? [], null);
        $this->setIfExists('creator', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('messages_cap', $data ?? [], null);
        $this->setIfExists('cost_cap', $data ?? [], null);
        $this->setIfExists('sms_cap', $data ?? [], null);
        $this->setIfExists('call_cap', $data ?? [], null);
        $this->setIfExists('billing_version', $data ?? [], null);
        $this->setIfExists('anniversary_date', $data ?? [], null);
        $this->setIfExists('allow_overage', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('session_id', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['organization_id'] === null) {
            $invalidProperties[] = "'organization_id' can't be null";
        }
        if ($this->container['organization_type'] === null) {
            $invalidProperties[] = "'organization_type' can't be null";
        }
        $allowedValues = $this->getOrganizationTypeAllowableValues();
        if (!is_null($this->container['organization_type']) && !in_array($this->container['organization_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'organization_type', must be one of '%s'",
                $this->container['organization_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['creator'] === null) {
            $invalidProperties[] = "'creator' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['messages_cap'] === null) {
            $invalidProperties[] = "'messages_cap' can't be null";
        }
        if ($this->container['cost_cap'] === null) {
            $invalidProperties[] = "'cost_cap' can't be null";
        }
        $allowedValues = $this->getBillingVersionAllowableValues();
        if (!is_null($this->container['billing_version']) && !in_array($this->container['billing_version'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'billing_version', must be one of '%s'",
                $this->container['billing_version'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['anniversary_date'] === null) {
            $invalidProperties[] = "'anniversary_date' can't be null";
        }
        if ($this->container['allow_overage'] === null) {
            $invalidProperties[] = "'allow_overage' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets organization_id
     *
     * @return string
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string $organization_id organization_id
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets organization_type
     *
     * @return string
     */
    public function getOrganizationType()
    {
        return $this->container['organization_type'];
    }

    /**
     * Sets organization_type
     *
     * @param string $organization_type organization_type
     *
     * @return self
     */
    public function setOrganizationType($organization_type)
    {
        if (is_null($organization_type)) {
            throw new \InvalidArgumentException('non-nullable organization_type cannot be null');
        }
        $allowedValues = $this->getOrganizationTypeAllowableValues();
        if (!in_array($organization_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'organization_type', must be one of '%s'",
                    $organization_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['organization_type'] = $organization_type;

        return $this;
    }

    /**
     * Gets creator
     *
     * @return string
     */
    public function getCreator()
    {
        return $this->container['creator'];
    }

    /**
     * Sets creator
     *
     * @param string $creator creator
     *
     * @return self
     */
    public function setCreator($creator)
    {
        if (is_null($creator)) {
            throw new \InvalidArgumentException('non-nullable creator cannot be null');
        }
        $this->container['creator'] = $creator;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets messages_cap
     *
     * @return float
     */
    public function getMessagesCap()
    {
        return $this->container['messages_cap'];
    }

    /**
     * Sets messages_cap
     *
     * @param float $messages_cap messages_cap
     *
     * @return self
     */
    public function setMessagesCap($messages_cap)
    {
        if (is_null($messages_cap)) {
            throw new \InvalidArgumentException('non-nullable messages_cap cannot be null');
        }
        $this->container['messages_cap'] = $messages_cap;

        return $this;
    }

    /**
     * Gets cost_cap
     *
     * @return float
     */
    public function getCostCap()
    {
        return $this->container['cost_cap'];
    }

    /**
     * Sets cost_cap
     *
     * @param float $cost_cap cost_cap
     *
     * @return self
     */
    public function setCostCap($cost_cap)
    {
        if (is_null($cost_cap)) {
            throw new \InvalidArgumentException('non-nullable cost_cap cannot be null');
        }
        $this->container['cost_cap'] = $cost_cap;

        return $this;
    }

    /**
     * Gets sms_cap
     *
     * @return float|null
     */
    public function getSmsCap()
    {
        return $this->container['sms_cap'];
    }

    /**
     * Sets sms_cap
     *
     * @param float|null $sms_cap sms_cap
     *
     * @return self
     */
    public function setSmsCap($sms_cap)
    {
        if (is_null($sms_cap)) {
            throw new \InvalidArgumentException('non-nullable sms_cap cannot be null');
        }
        $this->container['sms_cap'] = $sms_cap;

        return $this;
    }

    /**
     * Gets call_cap
     *
     * @return float|null
     */
    public function getCallCap()
    {
        return $this->container['call_cap'];
    }

    /**
     * Sets call_cap
     *
     * @param float|null $call_cap call_cap
     *
     * @return self
     */
    public function setCallCap($call_cap)
    {
        if (is_null($call_cap)) {
            throw new \InvalidArgumentException('non-nullable call_cap cannot be null');
        }
        $this->container['call_cap'] = $call_cap;

        return $this;
    }

    /**
     * Gets billing_version
     *
     * @return float|null
     */
    public function getBillingVersion()
    {
        return $this->container['billing_version'];
    }

    /**
     * Sets billing_version
     *
     * @param float|null $billing_version billing_version
     *
     * @return self
     */
    public function setBillingVersion($billing_version)
    {
        if (is_null($billing_version)) {
            throw new \InvalidArgumentException('non-nullable billing_version cannot be null');
        }
        $allowedValues = $this->getBillingVersionAllowableValues();
        if (!in_array($billing_version, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'billing_version', must be one of '%s'",
                    $billing_version,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['billing_version'] = $billing_version;

        return $this;
    }

    /**
     * Gets anniversary_date
     *
     * @return string
     */
    public function getAnniversaryDate()
    {
        return $this->container['anniversary_date'];
    }

    /**
     * Sets anniversary_date
     *
     * @param string $anniversary_date ISO date (YYYY-MM-DD) when the billing cycle resets.
     *
     * @return self
     */
    public function setAnniversaryDate($anniversary_date)
    {
        if (is_null($anniversary_date)) {
            throw new \InvalidArgumentException('non-nullable anniversary_date cannot be null');
        }
        $this->container['anniversary_date'] = $anniversary_date;

        return $this;
    }

    /**
     * Gets allow_overage
     *
     * @return bool
     */
    public function getAllowOverage()
    {
        return $this->container['allow_overage'];
    }

    /**
     * Sets allow_overage
     *
     * @param bool $allow_overage allow_overage
     *
     * @return self
     */
    public function setAllowOverage($allow_overage)
    {
        if (is_null($allow_overage)) {
            throw new \InvalidArgumentException('non-nullable allow_overage cannot be null');
        }
        $this->container['allow_overage'] = $allow_overage;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets session_id
     *
     * @return string|null
     */
    public function getSessionId()
    {
        return $this->container['session_id'];
    }

    /**
     * Sets session_id
     *
     * @param string|null $session_id session_id
     *
     * @return self
     */
    public function setSessionId($session_id)
    {
        if (is_null($session_id)) {
            throw new \InvalidArgumentException('non-nullable session_id cannot be null');
        }
        $this->container['session_id'] = $session_id;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


