<?php
/**
 * BindNumberResponseAgentSpecConversation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pingram
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * BindNumberResponseAgentSpecConversation Class Doc Comment
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BindNumberResponseAgentSpecConversation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BindNumberResponse_agent_spec_conversation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'turn_detection' => 'string',
        'min_end_of_turn_silence_ms' => 'float',
        'allow_interruptions' => 'bool',
        'min_interruption_duration_ms' => 'float',
        'silence_timeout_seconds' => 'float',
        'max_call_length_seconds' => 'float',
        'agent_can_end_call' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'turn_detection' => null,
        'min_end_of_turn_silence_ms' => null,
        'allow_interruptions' => null,
        'min_interruption_duration_ms' => null,
        'silence_timeout_seconds' => null,
        'max_call_length_seconds' => null,
        'agent_can_end_call' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'turn_detection' => false,
        'min_end_of_turn_silence_ms' => false,
        'allow_interruptions' => false,
        'min_interruption_duration_ms' => false,
        'silence_timeout_seconds' => false,
        'max_call_length_seconds' => false,
        'agent_can_end_call' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'turn_detection' => 'turnDetection',
        'min_end_of_turn_silence_ms' => 'minEndOfTurnSilenceMs',
        'allow_interruptions' => 'allowInterruptions',
        'min_interruption_duration_ms' => 'minInterruptionDurationMs',
        'silence_timeout_seconds' => 'silenceTimeoutSeconds',
        'max_call_length_seconds' => 'maxCallLengthSeconds',
        'agent_can_end_call' => 'agentCanEndCall'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'turn_detection' => 'setTurnDetection',
        'min_end_of_turn_silence_ms' => 'setMinEndOfTurnSilenceMs',
        'allow_interruptions' => 'setAllowInterruptions',
        'min_interruption_duration_ms' => 'setMinInterruptionDurationMs',
        'silence_timeout_seconds' => 'setSilenceTimeoutSeconds',
        'max_call_length_seconds' => 'setMaxCallLengthSeconds',
        'agent_can_end_call' => 'setAgentCanEndCall'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'turn_detection' => 'getTurnDetection',
        'min_end_of_turn_silence_ms' => 'getMinEndOfTurnSilenceMs',
        'allow_interruptions' => 'getAllowInterruptions',
        'min_interruption_duration_ms' => 'getMinInterruptionDurationMs',
        'silence_timeout_seconds' => 'getSilenceTimeoutSeconds',
        'max_call_length_seconds' => 'getMaxCallLengthSeconds',
        'agent_can_end_call' => 'getAgentCanEndCall'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TURN_DETECTION_SEMANTIC = 'semantic';
    public const TURN_DETECTION_VAD = 'vad';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTurnDetectionAllowableValues()
    {
        return [
            self::TURN_DETECTION_SEMANTIC,
            self::TURN_DETECTION_VAD,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('turn_detection', $data ?? [], null);
        $this->setIfExists('min_end_of_turn_silence_ms', $data ?? [], null);
        $this->setIfExists('allow_interruptions', $data ?? [], null);
        $this->setIfExists('min_interruption_duration_ms', $data ?? [], null);
        $this->setIfExists('silence_timeout_seconds', $data ?? [], null);
        $this->setIfExists('max_call_length_seconds', $data ?? [], null);
        $this->setIfExists('agent_can_end_call', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['turn_detection'] === null) {
            $invalidProperties[] = "'turn_detection' can't be null";
        }
        $allowedValues = $this->getTurnDetectionAllowableValues();
        if (!is_null($this->container['turn_detection']) && !in_array($this->container['turn_detection'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'turn_detection', must be one of '%s'",
                $this->container['turn_detection'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['min_end_of_turn_silence_ms'] === null) {
            $invalidProperties[] = "'min_end_of_turn_silence_ms' can't be null";
        }
        if ($this->container['allow_interruptions'] === null) {
            $invalidProperties[] = "'allow_interruptions' can't be null";
        }
        if ($this->container['min_interruption_duration_ms'] === null) {
            $invalidProperties[] = "'min_interruption_duration_ms' can't be null";
        }
        if ($this->container['silence_timeout_seconds'] === null) {
            $invalidProperties[] = "'silence_timeout_seconds' can't be null";
        }
        if ($this->container['max_call_length_seconds'] === null) {
            $invalidProperties[] = "'max_call_length_seconds' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets turn_detection
     *
     * @return string
     */
    public function getTurnDetection()
    {
        return $this->container['turn_detection'];
    }

    /**
     * Sets turn_detection
     *
     * @param string $turn_detection turn_detection
     *
     * @return self
     */
    public function setTurnDetection($turn_detection)
    {
        if (is_null($turn_detection)) {
            throw new \InvalidArgumentException('non-nullable turn_detection cannot be null');
        }
        $allowedValues = $this->getTurnDetectionAllowableValues();
        if (!in_array($turn_detection, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'turn_detection', must be one of '%s'",
                    $turn_detection,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['turn_detection'] = $turn_detection;

        return $this;
    }

    /**
     * Gets min_end_of_turn_silence_ms
     *
     * @return float
     */
    public function getMinEndOfTurnSilenceMs()
    {
        return $this->container['min_end_of_turn_silence_ms'];
    }

    /**
     * Sets min_end_of_turn_silence_ms
     *
     * @param float $min_end_of_turn_silence_ms min_end_of_turn_silence_ms
     *
     * @return self
     */
    public function setMinEndOfTurnSilenceMs($min_end_of_turn_silence_ms)
    {
        if (is_null($min_end_of_turn_silence_ms)) {
            throw new \InvalidArgumentException('non-nullable min_end_of_turn_silence_ms cannot be null');
        }
        $this->container['min_end_of_turn_silence_ms'] = $min_end_of_turn_silence_ms;

        return $this;
    }

    /**
     * Gets allow_interruptions
     *
     * @return bool
     */
    public function getAllowInterruptions()
    {
        return $this->container['allow_interruptions'];
    }

    /**
     * Sets allow_interruptions
     *
     * @param bool $allow_interruptions allow_interruptions
     *
     * @return self
     */
    public function setAllowInterruptions($allow_interruptions)
    {
        if (is_null($allow_interruptions)) {
            throw new \InvalidArgumentException('non-nullable allow_interruptions cannot be null');
        }
        $this->container['allow_interruptions'] = $allow_interruptions;

        return $this;
    }

    /**
     * Gets min_interruption_duration_ms
     *
     * @return float
     */
    public function getMinInterruptionDurationMs()
    {
        return $this->container['min_interruption_duration_ms'];
    }

    /**
     * Sets min_interruption_duration_ms
     *
     * @param float $min_interruption_duration_ms min_interruption_duration_ms
     *
     * @return self
     */
    public function setMinInterruptionDurationMs($min_interruption_duration_ms)
    {
        if (is_null($min_interruption_duration_ms)) {
            throw new \InvalidArgumentException('non-nullable min_interruption_duration_ms cannot be null');
        }
        $this->container['min_interruption_duration_ms'] = $min_interruption_duration_ms;

        return $this;
    }

    /**
     * Gets silence_timeout_seconds
     *
     * @return float
     */
    public function getSilenceTimeoutSeconds()
    {
        return $this->container['silence_timeout_seconds'];
    }

    /**
     * Sets silence_timeout_seconds
     *
     * @param float $silence_timeout_seconds silence_timeout_seconds
     *
     * @return self
     */
    public function setSilenceTimeoutSeconds($silence_timeout_seconds)
    {
        if (is_null($silence_timeout_seconds)) {
            throw new \InvalidArgumentException('non-nullable silence_timeout_seconds cannot be null');
        }
        $this->container['silence_timeout_seconds'] = $silence_timeout_seconds;

        return $this;
    }

    /**
     * Gets max_call_length_seconds
     *
     * @return float
     */
    public function getMaxCallLengthSeconds()
    {
        return $this->container['max_call_length_seconds'];
    }

    /**
     * Sets max_call_length_seconds
     *
     * @param float $max_call_length_seconds max_call_length_seconds
     *
     * @return self
     */
    public function setMaxCallLengthSeconds($max_call_length_seconds)
    {
        if (is_null($max_call_length_seconds)) {
            throw new \InvalidArgumentException('non-nullable max_call_length_seconds cannot be null');
        }
        $this->container['max_call_length_seconds'] = $max_call_length_seconds;

        return $this;
    }

    /**
     * Gets agent_can_end_call
     *
     * @return bool|null
     */
    public function getAgentCanEndCall()
    {
        return $this->container['agent_can_end_call'];
    }

    /**
     * Sets agent_can_end_call
     *
     * @param bool|null $agent_can_end_call When true (default), the agent may invoke the built-in end_call action.
     *
     * @return self
     */
    public function setAgentCanEndCall($agent_can_end_call)
    {
        if (is_null($agent_can_end_call)) {
            throw new \InvalidArgumentException('non-nullable agent_can_end_call cannot be null');
        }
        $this->container['agent_can_end_call'] = $agent_can_end_call;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


