<?php
/**
 * InAppNotificationPatchRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NotificationAPI
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * InAppNotificationPatchRequest Class Doc Comment
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InAppNotificationPatchRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InAppNotificationPatchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tracking_ids' => 'string[]',
        'opened' => 'string',
        'clicked' => 'string',
        'archived' => 'string',
        'actioned1' => 'string',
        'actioned2' => 'string',
        'reply' => '\Pingram\Model\GetInappNotificationsResponseNotificationsInnerRepliesInner',
        'replies' => '\Pingram\Model\GetInappNotificationsResponseNotificationsInnerRepliesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tracking_ids' => null,
        'opened' => null,
        'clicked' => null,
        'archived' => null,
        'actioned1' => null,
        'actioned2' => null,
        'reply' => null,
        'replies' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tracking_ids' => false,
        'opened' => false,
        'clicked' => false,
        'archived' => false,
        'actioned1' => false,
        'actioned2' => false,
        'reply' => false,
        'replies' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tracking_ids' => 'trackingIds',
        'opened' => 'opened',
        'clicked' => 'clicked',
        'archived' => 'archived',
        'actioned1' => 'actioned1',
        'actioned2' => 'actioned2',
        'reply' => 'reply',
        'replies' => 'replies'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tracking_ids' => 'setTrackingIds',
        'opened' => 'setOpened',
        'clicked' => 'setClicked',
        'archived' => 'setArchived',
        'actioned1' => 'setActioned1',
        'actioned2' => 'setActioned2',
        'reply' => 'setReply',
        'replies' => 'setReplies'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tracking_ids' => 'getTrackingIds',
        'opened' => 'getOpened',
        'clicked' => 'getClicked',
        'archived' => 'getArchived',
        'actioned1' => 'getActioned1',
        'actioned2' => 'getActioned2',
        'reply' => 'getReply',
        'replies' => 'getReplies'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tracking_ids', $data ?? [], null);
        $this->setIfExists('opened', $data ?? [], null);
        $this->setIfExists('clicked', $data ?? [], null);
        $this->setIfExists('archived', $data ?? [], null);
        $this->setIfExists('actioned1', $data ?? [], null);
        $this->setIfExists('actioned2', $data ?? [], null);
        $this->setIfExists('reply', $data ?? [], null);
        $this->setIfExists('replies', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tracking_ids'] === null) {
            $invalidProperties[] = "'tracking_ids' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tracking_ids
     *
     * @return string[]
     */
    public function getTrackingIds()
    {
        return $this->container['tracking_ids'];
    }

    /**
     * Sets tracking_ids
     *
     * @param string[] $tracking_ids tracking_ids
     *
     * @return self
     */
    public function setTrackingIds($tracking_ids)
    {
        if (is_null($tracking_ids)) {
            throw new \InvalidArgumentException('non-nullable tracking_ids cannot be null');
        }
        $this->container['tracking_ids'] = $tracking_ids;

        return $this;
    }

    /**
     * Gets opened
     *
     * @return string|null
     */
    public function getOpened()
    {
        return $this->container['opened'];
    }

    /**
     * Sets opened
     *
     * @param string|null $opened opened
     *
     * @return self
     */
    public function setOpened($opened)
    {
        if (is_null($opened)) {
            throw new \InvalidArgumentException('non-nullable opened cannot be null');
        }
        $this->container['opened'] = $opened;

        return $this;
    }

    /**
     * Gets clicked
     *
     * @return string|null
     */
    public function getClicked()
    {
        return $this->container['clicked'];
    }

    /**
     * Sets clicked
     *
     * @param string|null $clicked clicked
     *
     * @return self
     */
    public function setClicked($clicked)
    {
        if (is_null($clicked)) {
            throw new \InvalidArgumentException('non-nullable clicked cannot be null');
        }
        $this->container['clicked'] = $clicked;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return string|null
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param string|null $archived archived
     *
     * @return self
     */
    public function setArchived($archived)
    {
        if (is_null($archived)) {
            throw new \InvalidArgumentException('non-nullable archived cannot be null');
        }
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets actioned1
     *
     * @return string|null
     */
    public function getActioned1()
    {
        return $this->container['actioned1'];
    }

    /**
     * Sets actioned1
     *
     * @param string|null $actioned1 actioned1
     *
     * @return self
     */
    public function setActioned1($actioned1)
    {
        if (is_null($actioned1)) {
            throw new \InvalidArgumentException('non-nullable actioned1 cannot be null');
        }
        $this->container['actioned1'] = $actioned1;

        return $this;
    }

    /**
     * Gets actioned2
     *
     * @return string|null
     */
    public function getActioned2()
    {
        return $this->container['actioned2'];
    }

    /**
     * Sets actioned2
     *
     * @param string|null $actioned2 actioned2
     *
     * @return self
     */
    public function setActioned2($actioned2)
    {
        if (is_null($actioned2)) {
            throw new \InvalidArgumentException('non-nullable actioned2 cannot be null');
        }
        $this->container['actioned2'] = $actioned2;

        return $this;
    }

    /**
     * Gets reply
     *
     * @return \Pingram\Model\GetInappNotificationsResponseNotificationsInnerRepliesInner|null
     */
    public function getReply()
    {
        return $this->container['reply'];
    }

    /**
     * Sets reply
     *
     * @param \Pingram\Model\GetInappNotificationsResponseNotificationsInnerRepliesInner|null $reply reply
     *
     * @return self
     */
    public function setReply($reply)
    {
        if (is_null($reply)) {
            throw new \InvalidArgumentException('non-nullable reply cannot be null');
        }
        $this->container['reply'] = $reply;

        return $this;
    }

    /**
     * Gets replies
     *
     * @return \Pingram\Model\GetInappNotificationsResponseNotificationsInnerRepliesInner[]|null
     */
    public function getReplies()
    {
        return $this->container['replies'];
    }

    /**
     * Sets replies
     *
     * @param \Pingram\Model\GetInappNotificationsResponseNotificationsInnerRepliesInner[]|null $replies replies
     *
     * @return self
     */
    public function setReplies($replies)
    {
        if (is_null($replies)) {
            throw new \InvalidArgumentException('non-nullable replies cannot be null');
        }
        $this->container['replies'] = $replies;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


