<?php
/**
 * IngishtsPostRequestMetricDataQueriesInnerMetricStat
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * NotificationAPI
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * IngishtsPostRequestMetricDataQueriesInnerMetricStat Class Doc Comment
 *
 * @category Class
 * @description &lt;p&gt;This structure defines the metric to be returned, along with the statistics, period,             and units.&lt;/p&gt;
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IngishtsPostRequestMetricDataQueriesInnerMetricStat implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'IngishtsPostRequest_MetricDataQueries_inner_MetricStat';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'metric' => '\Pingram\Model\IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric',
        'period' => 'float',
        'stat' => 'string',
        'unit' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'metric' => null,
        'period' => null,
        'stat' => null,
        'unit' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'metric' => false,
        'period' => false,
        'stat' => false,
        'unit' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'metric' => 'Metric',
        'period' => 'Period',
        'stat' => 'Stat',
        'unit' => 'Unit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'metric' => 'setMetric',
        'period' => 'setPeriod',
        'stat' => 'setStat',
        'unit' => 'setUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'metric' => 'getMetric',
        'period' => 'getPeriod',
        'stat' => 'getStat',
        'unit' => 'getUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const UNIT_BITS = 'Bits';
    public const UNIT_BITS_SECOND = 'Bits/Second';
    public const UNIT_BYTES = 'Bytes';
    public const UNIT_BYTES_SECOND = 'Bytes/Second';
    public const UNIT_COUNT = 'Count';
    public const UNIT_COUNT_SECOND = 'Count/Second';
    public const UNIT_GIGABITS = 'Gigabits';
    public const UNIT_GIGABITS_SECOND = 'Gigabits/Second';
    public const UNIT_GIGABYTES = 'Gigabytes';
    public const UNIT_GIGABYTES_SECOND = 'Gigabytes/Second';
    public const UNIT_KILOBITS = 'Kilobits';
    public const UNIT_KILOBITS_SECOND = 'Kilobits/Second';
    public const UNIT_KILOBYTES = 'Kilobytes';
    public const UNIT_KILOBYTES_SECOND = 'Kilobytes/Second';
    public const UNIT_MEGABITS = 'Megabits';
    public const UNIT_MEGABITS_SECOND = 'Megabits/Second';
    public const UNIT_MEGABYTES = 'Megabytes';
    public const UNIT_MEGABYTES_SECOND = 'Megabytes/Second';
    public const UNIT_MICROSECONDS = 'Microseconds';
    public const UNIT_MILLISECONDS = 'Milliseconds';
    public const UNIT_NONE = 'None';
    public const UNIT_PERCENT = 'Percent';
    public const UNIT_SECONDS = 'Seconds';
    public const UNIT_TERABITS = 'Terabits';
    public const UNIT_TERABITS_SECOND = 'Terabits/Second';
    public const UNIT_TERABYTES = 'Terabytes';
    public const UNIT_TERABYTES_SECOND = 'Terabytes/Second';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getUnitAllowableValues()
    {
        return [
            self::UNIT_BITS,
            self::UNIT_BITS_SECOND,
            self::UNIT_BYTES,
            self::UNIT_BYTES_SECOND,
            self::UNIT_COUNT,
            self::UNIT_COUNT_SECOND,
            self::UNIT_GIGABITS,
            self::UNIT_GIGABITS_SECOND,
            self::UNIT_GIGABYTES,
            self::UNIT_GIGABYTES_SECOND,
            self::UNIT_KILOBITS,
            self::UNIT_KILOBITS_SECOND,
            self::UNIT_KILOBYTES,
            self::UNIT_KILOBYTES_SECOND,
            self::UNIT_MEGABITS,
            self::UNIT_MEGABITS_SECOND,
            self::UNIT_MEGABYTES,
            self::UNIT_MEGABYTES_SECOND,
            self::UNIT_MICROSECONDS,
            self::UNIT_MILLISECONDS,
            self::UNIT_NONE,
            self::UNIT_PERCENT,
            self::UNIT_SECONDS,
            self::UNIT_TERABITS,
            self::UNIT_TERABITS_SECOND,
            self::UNIT_TERABYTES,
            self::UNIT_TERABYTES_SECOND,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('metric', $data ?? [], null);
        $this->setIfExists('period', $data ?? [], null);
        $this->setIfExists('stat', $data ?? [], null);
        $this->setIfExists('unit', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getUnitAllowableValues();
        if (!is_null($this->container['unit']) && !in_array($this->container['unit'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'unit', must be one of '%s'",
                $this->container['unit'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets metric
     *
     * @return \Pingram\Model\IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric|null
     */
    public function getMetric()
    {
        return $this->container['metric'];
    }

    /**
     * Sets metric
     *
     * @param \Pingram\Model\IngishtsPostRequestMetricDataQueriesInnerMetricStatMetric|null $metric metric
     *
     * @return self
     */
    public function setMetric($metric)
    {
        if (is_null($metric)) {
            throw new \InvalidArgumentException('non-nullable metric cannot be null');
        }
        $this->container['metric'] = $metric;

        return $this;
    }

    /**
     * Gets period
     *
     * @return float|null
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param float|null $period <p>The granularity, in seconds, of the returned data points. For metrics with regular             resolution, a period can be as short as one minute (60 seconds) and must be a multiple             of 60. For high-resolution metrics that are collected at intervals of less than one             minute, the period can be 1, 5, 10, 20, 30, 60, or any multiple of 60. High-resolution             metrics are those metrics stored by a <code>PutMetricData</code> call that includes a             <code>StorageResolution</code> of 1 second.</p>          <p>If the <code>StartTime</code> parameter specifies a time stamp that is greater than             3 hours ago, you must specify the period as follows or no data points in that time range             is returned:</p>          <ul>             <li>                <p>Start time between 3 hours and 15 days ago - Use a multiple of 60 seconds                     (1 minute).</p>             </li>             <li>                <p>Start time between 15 and 63 days ago - Use a multiple of 300 seconds (5                     minutes).</p>             </li>             <li>                <p>Start time greater than 63 days ago - Use a multiple of 3600 seconds (1                     hour).</p>             </li>          </ul>
     *
     * @return self
     */
    public function setPeriod($period)
    {
        if (is_null($period)) {
            throw new \InvalidArgumentException('non-nullable period cannot be null');
        }
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets stat
     *
     * @return string|null
     */
    public function getStat()
    {
        return $this->container['stat'];
    }

    /**
     * Sets stat
     *
     * @param string|null $stat <p>The statistic to return. It can include any CloudWatch statistic or extended             statistic.</p>
     *
     * @return self
     */
    public function setStat($stat)
    {
        if (is_null($stat)) {
            throw new \InvalidArgumentException('non-nullable stat cannot be null');
        }
        $this->container['stat'] = $stat;

        return $this;
    }

    /**
     * Gets unit
     *
     * @return string|null
     */
    public function getUnit()
    {
        return $this->container['unit'];
    }

    /**
     * Sets unit
     *
     * @param string|null $unit unit
     *
     * @return self
     */
    public function setUnit($unit)
    {
        if (is_null($unit)) {
            throw new \InvalidArgumentException('non-nullable unit cannot be null');
        }
        $allowedValues = $this->getUnitAllowableValues();
        if (!in_array($unit, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'unit', must be one of '%s'",
                    $unit,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['unit'] = $unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


