<?php
/**
 * IngishtsPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pingram
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * IngishtsPostRequest Class Doc Comment
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IngishtsPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'IngishtsPostRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'start_time' => 'string',
        'end_time' => 'string',
        'metric_data_queries' => '\Pingram\Model\IngishtsPostRequestMetricDataQueriesInner[]',
        'next_token' => 'string',
        'scan_by' => 'string',
        'max_datapoints' => 'float',
        'label_options' => '\Pingram\Model\IngishtsPostRequestLabelOptions'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'start_time' => null,
        'end_time' => null,
        'metric_data_queries' => null,
        'next_token' => null,
        'scan_by' => null,
        'max_datapoints' => null,
        'label_options' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'start_time' => false,
        'end_time' => false,
        'metric_data_queries' => false,
        'next_token' => false,
        'scan_by' => false,
        'max_datapoints' => false,
        'label_options' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'start_time' => 'StartTime',
        'end_time' => 'EndTime',
        'metric_data_queries' => 'MetricDataQueries',
        'next_token' => 'NextToken',
        'scan_by' => 'ScanBy',
        'max_datapoints' => 'MaxDatapoints',
        'label_options' => 'LabelOptions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'start_time' => 'setStartTime',
        'end_time' => 'setEndTime',
        'metric_data_queries' => 'setMetricDataQueries',
        'next_token' => 'setNextToken',
        'scan_by' => 'setScanBy',
        'max_datapoints' => 'setMaxDatapoints',
        'label_options' => 'setLabelOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'start_time' => 'getStartTime',
        'end_time' => 'getEndTime',
        'metric_data_queries' => 'getMetricDataQueries',
        'next_token' => 'getNextToken',
        'scan_by' => 'getScanBy',
        'max_datapoints' => 'getMaxDatapoints',
        'label_options' => 'getLabelOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SCAN_BY_TIMESTAMP_DESCENDING = 'TimestampDescending';
    public const SCAN_BY_TIMESTAMP_ASCENDING = 'TimestampAscending';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScanByAllowableValues()
    {
        return [
            self::SCAN_BY_TIMESTAMP_DESCENDING,
            self::SCAN_BY_TIMESTAMP_ASCENDING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('start_time', $data ?? [], null);
        $this->setIfExists('end_time', $data ?? [], null);
        $this->setIfExists('metric_data_queries', $data ?? [], null);
        $this->setIfExists('next_token', $data ?? [], null);
        $this->setIfExists('scan_by', $data ?? [], null);
        $this->setIfExists('max_datapoints', $data ?? [], null);
        $this->setIfExists('label_options', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['start_time'] === null) {
            $invalidProperties[] = "'start_time' can't be null";
        }
        if ($this->container['end_time'] === null) {
            $invalidProperties[] = "'end_time' can't be null";
        }
        if ($this->container['metric_data_queries'] === null) {
            $invalidProperties[] = "'metric_data_queries' can't be null";
        }
        $allowedValues = $this->getScanByAllowableValues();
        if (!is_null($this->container['scan_by']) && !in_array($this->container['scan_by'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'scan_by', must be one of '%s'",
                $this->container['scan_by'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets start_time
     *
     * @return string
     */
    public function getStartTime()
    {
        return $this->container['start_time'];
    }

    /**
     * Sets start_time
     *
     * @param string $start_time start_time
     *
     * @return self
     */
    public function setStartTime($start_time)
    {
        if (is_null($start_time)) {
            throw new \InvalidArgumentException('non-nullable start_time cannot be null');
        }
        $this->container['start_time'] = $start_time;

        return $this;
    }

    /**
     * Gets end_time
     *
     * @return string
     */
    public function getEndTime()
    {
        return $this->container['end_time'];
    }

    /**
     * Sets end_time
     *
     * @param string $end_time end_time
     *
     * @return self
     */
    public function setEndTime($end_time)
    {
        if (is_null($end_time)) {
            throw new \InvalidArgumentException('non-nullable end_time cannot be null');
        }
        $this->container['end_time'] = $end_time;

        return $this;
    }

    /**
     * Gets metric_data_queries
     *
     * @return \Pingram\Model\IngishtsPostRequestMetricDataQueriesInner[]
     */
    public function getMetricDataQueries()
    {
        return $this->container['metric_data_queries'];
    }

    /**
     * Sets metric_data_queries
     *
     * @param \Pingram\Model\IngishtsPostRequestMetricDataQueriesInner[] $metric_data_queries metric_data_queries
     *
     * @return self
     */
    public function setMetricDataQueries($metric_data_queries)
    {
        if (is_null($metric_data_queries)) {
            throw new \InvalidArgumentException('non-nullable metric_data_queries cannot be null');
        }
        $this->container['metric_data_queries'] = $metric_data_queries;

        return $this;
    }

    /**
     * Gets next_token
     *
     * @return string|null
     */
    public function getNextToken()
    {
        return $this->container['next_token'];
    }

    /**
     * Sets next_token
     *
     * @param string|null $next_token next_token
     *
     * @return self
     */
    public function setNextToken($next_token)
    {
        if (is_null($next_token)) {
            throw new \InvalidArgumentException('non-nullable next_token cannot be null');
        }
        $this->container['next_token'] = $next_token;

        return $this;
    }

    /**
     * Gets scan_by
     *
     * @return string|null
     */
    public function getScanBy()
    {
        return $this->container['scan_by'];
    }

    /**
     * Sets scan_by
     *
     * @param string|null $scan_by scan_by
     *
     * @return self
     */
    public function setScanBy($scan_by)
    {
        if (is_null($scan_by)) {
            throw new \InvalidArgumentException('non-nullable scan_by cannot be null');
        }
        $allowedValues = $this->getScanByAllowableValues();
        if (!in_array($scan_by, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'scan_by', must be one of '%s'",
                    $scan_by,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['scan_by'] = $scan_by;

        return $this;
    }

    /**
     * Gets max_datapoints
     *
     * @return float|null
     */
    public function getMaxDatapoints()
    {
        return $this->container['max_datapoints'];
    }

    /**
     * Sets max_datapoints
     *
     * @param float|null $max_datapoints max_datapoints
     *
     * @return self
     */
    public function setMaxDatapoints($max_datapoints)
    {
        if (is_null($max_datapoints)) {
            throw new \InvalidArgumentException('non-nullable max_datapoints cannot be null');
        }
        $this->container['max_datapoints'] = $max_datapoints;

        return $this;
    }

    /**
     * Gets label_options
     *
     * @return \Pingram\Model\IngishtsPostRequestLabelOptions|null
     */
    public function getLabelOptions()
    {
        return $this->container['label_options'];
    }

    /**
     * Sets label_options
     *
     * @param \Pingram\Model\IngishtsPostRequestLabelOptions|null $label_options label_options
     *
     * @return self
     */
    public function setLabelOptions($label_options)
    {
        if (is_null($label_options)) {
            throw new \InvalidArgumentException('non-nullable label_options cannot be null');
        }
        $this->container['label_options'] = $label_options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


