<?php
/**
 * ListPhoneNumbersResponseNumbersInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pingram
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * ListPhoneNumbersResponseNumbersInner Class Doc Comment
 *
 * @category Class
 * @description Represents a phone number in the account
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ListPhoneNumbersResponseNumbersInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ListPhoneNumbersResponse_numbers_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'phone_number' => 'string',
        'label' => 'string',
        'created_at' => 'string',
        'country_code' => 'string',
        'number_type' => 'string',
        'billing_status' => 'string',
        'next_billing_date' => 'string',
        'monthly_price' => 'float',
        'a2p_status' => 'string',
        'released_at' => 'string',
        'bound_agent_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'phone_number' => null,
        'label' => null,
        'created_at' => null,
        'country_code' => null,
        'number_type' => null,
        'billing_status' => null,
        'next_billing_date' => null,
        'monthly_price' => null,
        'a2p_status' => null,
        'released_at' => null,
        'bound_agent_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'phone_number' => false,
        'label' => false,
        'created_at' => false,
        'country_code' => false,
        'number_type' => false,
        'billing_status' => false,
        'next_billing_date' => false,
        'monthly_price' => false,
        'a2p_status' => false,
        'released_at' => false,
        'bound_agent_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'phone_number' => 'phoneNumber',
        'label' => 'label',
        'created_at' => 'createdAt',
        'country_code' => 'countryCode',
        'number_type' => 'numberType',
        'billing_status' => 'billingStatus',
        'next_billing_date' => 'nextBillingDate',
        'monthly_price' => 'monthlyPrice',
        'a2p_status' => 'a2pStatus',
        'released_at' => 'releasedAt',
        'bound_agent_id' => 'boundAgentId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'phone_number' => 'setPhoneNumber',
        'label' => 'setLabel',
        'created_at' => 'setCreatedAt',
        'country_code' => 'setCountryCode',
        'number_type' => 'setNumberType',
        'billing_status' => 'setBillingStatus',
        'next_billing_date' => 'setNextBillingDate',
        'monthly_price' => 'setMonthlyPrice',
        'a2p_status' => 'setA2pStatus',
        'released_at' => 'setReleasedAt',
        'bound_agent_id' => 'setBoundAgentId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'phone_number' => 'getPhoneNumber',
        'label' => 'getLabel',
        'created_at' => 'getCreatedAt',
        'country_code' => 'getCountryCode',
        'number_type' => 'getNumberType',
        'billing_status' => 'getBillingStatus',
        'next_billing_date' => 'getNextBillingDate',
        'monthly_price' => 'getMonthlyPrice',
        'a2p_status' => 'getA2pStatus',
        'released_at' => 'getReleasedAt',
        'bound_agent_id' => 'getBoundAgentId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BILLING_STATUS_ACTIVE = 'active';
    public const BILLING_STATUS_RELEASED = 'released';
    public const A2P_STATUS_PENDING = 'pending';
    public const A2P_STATUS_TESTING = 'testing';
    public const A2P_STATUS_APPROVED = 'approved';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBillingStatusAllowableValues()
    {
        return [
            self::BILLING_STATUS_ACTIVE,
            self::BILLING_STATUS_RELEASED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getA2pStatusAllowableValues()
    {
        return [
            self::A2P_STATUS_PENDING,
            self::A2P_STATUS_TESTING,
            self::A2P_STATUS_APPROVED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('country_code', $data ?? [], null);
        $this->setIfExists('number_type', $data ?? [], null);
        $this->setIfExists('billing_status', $data ?? [], null);
        $this->setIfExists('next_billing_date', $data ?? [], null);
        $this->setIfExists('monthly_price', $data ?? [], null);
        $this->setIfExists('a2p_status', $data ?? [], null);
        $this->setIfExists('released_at', $data ?? [], null);
        $this->setIfExists('bound_agent_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['phone_number'] === null) {
            $invalidProperties[] = "'phone_number' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['country_code'] === null) {
            $invalidProperties[] = "'country_code' can't be null";
        }
        if ($this->container['number_type'] === null) {
            $invalidProperties[] = "'number_type' can't be null";
        }
        if ($this->container['billing_status'] === null) {
            $invalidProperties[] = "'billing_status' can't be null";
        }
        $allowedValues = $this->getBillingStatusAllowableValues();
        if (!is_null($this->container['billing_status']) && !in_array($this->container['billing_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'billing_status', must be one of '%s'",
                $this->container['billing_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['next_billing_date'] === null) {
            $invalidProperties[] = "'next_billing_date' can't be null";
        }
        if ($this->container['monthly_price'] === null) {
            $invalidProperties[] = "'monthly_price' can't be null";
        }
        $allowedValues = $this->getA2pStatusAllowableValues();
        if (!is_null($this->container['a2p_status']) && !in_array($this->container['a2p_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'a2p_status', must be one of '%s'",
                $this->container['a2p_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets phone_number
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string $phone_number E.164
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            throw new \InvalidArgumentException('non-nullable phone_number cannot be null');
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at ISO timestamp when the number was registered
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets country_code
     *
     * @return string
     */
    public function getCountryCode()
    {
        return $this->container['country_code'];
    }

    /**
     * Sets country_code
     *
     * @param string $country_code ISO 3166-1 alpha-2 country code
     *
     * @return self
     */
    public function setCountryCode($country_code)
    {
        if (is_null($country_code)) {
            throw new \InvalidArgumentException('non-nullable country_code cannot be null');
        }
        $this->container['country_code'] = $country_code;

        return $this;
    }

    /**
     * Gets number_type
     *
     * @return string
     */
    public function getNumberType()
    {
        return $this->container['number_type'];
    }

    /**
     * Sets number_type
     *
     * @param string $number_type e.g. local, toll_free
     *
     * @return self
     */
    public function setNumberType($number_type)
    {
        if (is_null($number_type)) {
            throw new \InvalidArgumentException('non-nullable number_type cannot be null');
        }
        $this->container['number_type'] = $number_type;

        return $this;
    }

    /**
     * Gets billing_status
     *
     * @return string
     */
    public function getBillingStatus()
    {
        return $this->container['billing_status'];
    }

    /**
     * Sets billing_status
     *
     * @param string $billing_status active or released
     *
     * @return self
     */
    public function setBillingStatus($billing_status)
    {
        if (is_null($billing_status)) {
            throw new \InvalidArgumentException('non-nullable billing_status cannot be null');
        }
        $allowedValues = $this->getBillingStatusAllowableValues();
        if (!in_array($billing_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'billing_status', must be one of '%s'",
                    $billing_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['billing_status'] = $billing_status;

        return $this;
    }

    /**
     * Gets next_billing_date
     *
     * @return string
     */
    public function getNextBillingDate()
    {
        return $this->container['next_billing_date'];
    }

    /**
     * Sets next_billing_date
     *
     * @param string $next_billing_date YYYY-MM-DD next monthly rent charge
     *
     * @return self
     */
    public function setNextBillingDate($next_billing_date)
    {
        if (is_null($next_billing_date)) {
            throw new \InvalidArgumentException('non-nullable next_billing_date cannot be null');
        }
        $this->container['next_billing_date'] = $next_billing_date;

        return $this;
    }

    /**
     * Gets monthly_price
     *
     * @return float
     */
    public function getMonthlyPrice()
    {
        return $this->container['monthly_price'];
    }

    /**
     * Sets monthly_price
     *
     * @param float $monthly_price Monthly cost in USD
     *
     * @return self
     */
    public function setMonthlyPrice($monthly_price)
    {
        if (is_null($monthly_price)) {
            throw new \InvalidArgumentException('non-nullable monthly_price cannot be null');
        }
        $this->container['monthly_price'] = $monthly_price;

        return $this;
    }

    /**
     * Gets a2p_status
     *
     * @return string|null
     */
    public function getA2pStatus()
    {
        return $this->container['a2p_status'];
    }

    /**
     * Sets a2p_status
     *
     * @param string|null $a2p_status US 10DLC readiness derived from stored campaign assignment
     *
     * @return self
     */
    public function setA2pStatus($a2p_status)
    {
        if (is_null($a2p_status)) {
            throw new \InvalidArgumentException('non-nullable a2p_status cannot be null');
        }
        $allowedValues = $this->getA2pStatusAllowableValues();
        if (!in_array($a2p_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'a2p_status', must be one of '%s'",
                    $a2p_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['a2p_status'] = $a2p_status;

        return $this;
    }

    /**
     * Gets released_at
     *
     * @return string|null
     */
    public function getReleasedAt()
    {
        return $this->container['released_at'];
    }

    /**
     * Sets released_at
     *
     * @param string|null $released_at ISO timestamp when the number was released (released numbers only)
     *
     * @return self
     */
    public function setReleasedAt($released_at)
    {
        if (is_null($released_at)) {
            throw new \InvalidArgumentException('non-nullable released_at cannot be null');
        }
        $this->container['released_at'] = $released_at;

        return $this;
    }

    /**
     * Gets bound_agent_id
     *
     * @return string|null
     */
    public function getBoundAgentId()
    {
        return $this->container['bound_agent_id'];
    }

    /**
     * Sets bound_agent_id
     *
     * @param string|null $bound_agent_id Voice agent id bound for inbound AI voice, if any
     *
     * @return self
     */
    public function setBoundAgentId($bound_agent_id)
    {
        if (is_null($bound_agent_id)) {
            throw new \InvalidArgumentException('non-nullable bound_agent_id cannot be null');
        }
        $this->container['bound_agent_id'] = $bound_agent_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


