<?php
/**
 * TenDlcCampaignUpdateRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pingram
 *
 * Internal API for notification delivery and management
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pingram\Model;

use \ArrayAccess;
use \Pingram\ObjectSerializer;

/**
 * TenDlcCampaignUpdateRequest Class Doc Comment
 *
 * @category Class
 * @description Request body for PATCH /registrations/us/10dlc/campaign (admin only)
 * @package  Pingram
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TenDlcCampaignUpdateRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TenDlcCampaignUpdateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'campaign_description' => 'string',
        'campaign_sample1' => 'string',
        'campaign_sample2' => 'string',
        'campaign_sample3' => 'string',
        'campaign_sample4' => 'string',
        'campaign_message_flow' => 'string',
        'campaign_optin_keywords' => 'string',
        'campaign_optin_message' => 'string',
        'campaign_optout_keywords' => 'string',
        'campaign_optout_message' => 'string',
        'campaign_help_keywords' => 'string',
        'campaign_help_message' => 'string',
        'campaign_embedded_link' => 'bool',
        'campaign_embedded_link_url' => 'string',
        'campaign_embedded_phone' => 'bool',
        'campaign_age_gated' => 'bool',
        'campaign_direct_lending' => 'bool',
        'campaign_privacy_policy_link' => 'string',
        'campaign_terms_and_conditions_link' => 'string',
        'campaign_usecase' => 'string',
        'campaign_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'campaign_description' => null,
        'campaign_sample1' => null,
        'campaign_sample2' => null,
        'campaign_sample3' => null,
        'campaign_sample4' => null,
        'campaign_message_flow' => null,
        'campaign_optin_keywords' => null,
        'campaign_optin_message' => null,
        'campaign_optout_keywords' => null,
        'campaign_optout_message' => null,
        'campaign_help_keywords' => null,
        'campaign_help_message' => null,
        'campaign_embedded_link' => null,
        'campaign_embedded_link_url' => null,
        'campaign_embedded_phone' => null,
        'campaign_age_gated' => null,
        'campaign_direct_lending' => null,
        'campaign_privacy_policy_link' => null,
        'campaign_terms_and_conditions_link' => null,
        'campaign_usecase' => null,
        'campaign_status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'campaign_description' => false,
        'campaign_sample1' => false,
        'campaign_sample2' => false,
        'campaign_sample3' => false,
        'campaign_sample4' => false,
        'campaign_message_flow' => false,
        'campaign_optin_keywords' => false,
        'campaign_optin_message' => false,
        'campaign_optout_keywords' => false,
        'campaign_optout_message' => false,
        'campaign_help_keywords' => false,
        'campaign_help_message' => false,
        'campaign_embedded_link' => false,
        'campaign_embedded_link_url' => false,
        'campaign_embedded_phone' => false,
        'campaign_age_gated' => false,
        'campaign_direct_lending' => false,
        'campaign_privacy_policy_link' => false,
        'campaign_terms_and_conditions_link' => false,
        'campaign_usecase' => false,
        'campaign_status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'campaign_description' => 'campaignDescription',
        'campaign_sample1' => 'campaignSample1',
        'campaign_sample2' => 'campaignSample2',
        'campaign_sample3' => 'campaignSample3',
        'campaign_sample4' => 'campaignSample4',
        'campaign_message_flow' => 'campaignMessageFlow',
        'campaign_optin_keywords' => 'campaignOptinKeywords',
        'campaign_optin_message' => 'campaignOptinMessage',
        'campaign_optout_keywords' => 'campaignOptoutKeywords',
        'campaign_optout_message' => 'campaignOptoutMessage',
        'campaign_help_keywords' => 'campaignHelpKeywords',
        'campaign_help_message' => 'campaignHelpMessage',
        'campaign_embedded_link' => 'campaignEmbeddedLink',
        'campaign_embedded_link_url' => 'campaignEmbeddedLinkUrl',
        'campaign_embedded_phone' => 'campaignEmbeddedPhone',
        'campaign_age_gated' => 'campaignAgeGated',
        'campaign_direct_lending' => 'campaignDirectLending',
        'campaign_privacy_policy_link' => 'campaignPrivacyPolicyLink',
        'campaign_terms_and_conditions_link' => 'campaignTermsAndConditionsLink',
        'campaign_usecase' => 'campaignUsecase',
        'campaign_status' => 'campaignStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'campaign_description' => 'setCampaignDescription',
        'campaign_sample1' => 'setCampaignSample1',
        'campaign_sample2' => 'setCampaignSample2',
        'campaign_sample3' => 'setCampaignSample3',
        'campaign_sample4' => 'setCampaignSample4',
        'campaign_message_flow' => 'setCampaignMessageFlow',
        'campaign_optin_keywords' => 'setCampaignOptinKeywords',
        'campaign_optin_message' => 'setCampaignOptinMessage',
        'campaign_optout_keywords' => 'setCampaignOptoutKeywords',
        'campaign_optout_message' => 'setCampaignOptoutMessage',
        'campaign_help_keywords' => 'setCampaignHelpKeywords',
        'campaign_help_message' => 'setCampaignHelpMessage',
        'campaign_embedded_link' => 'setCampaignEmbeddedLink',
        'campaign_embedded_link_url' => 'setCampaignEmbeddedLinkUrl',
        'campaign_embedded_phone' => 'setCampaignEmbeddedPhone',
        'campaign_age_gated' => 'setCampaignAgeGated',
        'campaign_direct_lending' => 'setCampaignDirectLending',
        'campaign_privacy_policy_link' => 'setCampaignPrivacyPolicyLink',
        'campaign_terms_and_conditions_link' => 'setCampaignTermsAndConditionsLink',
        'campaign_usecase' => 'setCampaignUsecase',
        'campaign_status' => 'setCampaignStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'campaign_description' => 'getCampaignDescription',
        'campaign_sample1' => 'getCampaignSample1',
        'campaign_sample2' => 'getCampaignSample2',
        'campaign_sample3' => 'getCampaignSample3',
        'campaign_sample4' => 'getCampaignSample4',
        'campaign_message_flow' => 'getCampaignMessageFlow',
        'campaign_optin_keywords' => 'getCampaignOptinKeywords',
        'campaign_optin_message' => 'getCampaignOptinMessage',
        'campaign_optout_keywords' => 'getCampaignOptoutKeywords',
        'campaign_optout_message' => 'getCampaignOptoutMessage',
        'campaign_help_keywords' => 'getCampaignHelpKeywords',
        'campaign_help_message' => 'getCampaignHelpMessage',
        'campaign_embedded_link' => 'getCampaignEmbeddedLink',
        'campaign_embedded_link_url' => 'getCampaignEmbeddedLinkUrl',
        'campaign_embedded_phone' => 'getCampaignEmbeddedPhone',
        'campaign_age_gated' => 'getCampaignAgeGated',
        'campaign_direct_lending' => 'getCampaignDirectLending',
        'campaign_privacy_policy_link' => 'getCampaignPrivacyPolicyLink',
        'campaign_terms_and_conditions_link' => 'getCampaignTermsAndConditionsLink',
        'campaign_usecase' => 'getCampaignUsecase',
        'campaign_status' => 'getCampaignStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CAMPAIGN_STATUS_NOT_STARTED = 'not_started';
    public const CAMPAIGN_STATUS_IN_PROGRESS = 'in_progress';
    public const CAMPAIGN_STATUS_PENDING_REVIEW = 'pending_review';
    public const CAMPAIGN_STATUS_APPROVED = 'approved';
    public const CAMPAIGN_STATUS_REJECTED = 'rejected';
    public const CAMPAIGN_STATUS_INFO_NEEDED = 'info_needed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCampaignStatusAllowableValues()
    {
        return [
            self::CAMPAIGN_STATUS_NOT_STARTED,
            self::CAMPAIGN_STATUS_IN_PROGRESS,
            self::CAMPAIGN_STATUS_PENDING_REVIEW,
            self::CAMPAIGN_STATUS_APPROVED,
            self::CAMPAIGN_STATUS_REJECTED,
            self::CAMPAIGN_STATUS_INFO_NEEDED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('campaign_description', $data ?? [], null);
        $this->setIfExists('campaign_sample1', $data ?? [], null);
        $this->setIfExists('campaign_sample2', $data ?? [], null);
        $this->setIfExists('campaign_sample3', $data ?? [], null);
        $this->setIfExists('campaign_sample4', $data ?? [], null);
        $this->setIfExists('campaign_message_flow', $data ?? [], null);
        $this->setIfExists('campaign_optin_keywords', $data ?? [], null);
        $this->setIfExists('campaign_optin_message', $data ?? [], null);
        $this->setIfExists('campaign_optout_keywords', $data ?? [], null);
        $this->setIfExists('campaign_optout_message', $data ?? [], null);
        $this->setIfExists('campaign_help_keywords', $data ?? [], null);
        $this->setIfExists('campaign_help_message', $data ?? [], null);
        $this->setIfExists('campaign_embedded_link', $data ?? [], null);
        $this->setIfExists('campaign_embedded_link_url', $data ?? [], null);
        $this->setIfExists('campaign_embedded_phone', $data ?? [], null);
        $this->setIfExists('campaign_age_gated', $data ?? [], null);
        $this->setIfExists('campaign_direct_lending', $data ?? [], null);
        $this->setIfExists('campaign_privacy_policy_link', $data ?? [], null);
        $this->setIfExists('campaign_terms_and_conditions_link', $data ?? [], null);
        $this->setIfExists('campaign_usecase', $data ?? [], null);
        $this->setIfExists('campaign_status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCampaignStatusAllowableValues();
        if (!is_null($this->container['campaign_status']) && !in_array($this->container['campaign_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'campaign_status', must be one of '%s'",
                $this->container['campaign_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets campaign_description
     *
     * @return string|null
     */
    public function getCampaignDescription()
    {
        return $this->container['campaign_description'];
    }

    /**
     * Sets campaign_description
     *
     * @param string|null $campaign_description campaign_description
     *
     * @return self
     */
    public function setCampaignDescription($campaign_description)
    {
        if (is_null($campaign_description)) {
            throw new \InvalidArgumentException('non-nullable campaign_description cannot be null');
        }
        $this->container['campaign_description'] = $campaign_description;

        return $this;
    }

    /**
     * Gets campaign_sample1
     *
     * @return string|null
     */
    public function getCampaignSample1()
    {
        return $this->container['campaign_sample1'];
    }

    /**
     * Sets campaign_sample1
     *
     * @param string|null $campaign_sample1 campaign_sample1
     *
     * @return self
     */
    public function setCampaignSample1($campaign_sample1)
    {
        if (is_null($campaign_sample1)) {
            throw new \InvalidArgumentException('non-nullable campaign_sample1 cannot be null');
        }
        $this->container['campaign_sample1'] = $campaign_sample1;

        return $this;
    }

    /**
     * Gets campaign_sample2
     *
     * @return string|null
     */
    public function getCampaignSample2()
    {
        return $this->container['campaign_sample2'];
    }

    /**
     * Sets campaign_sample2
     *
     * @param string|null $campaign_sample2 campaign_sample2
     *
     * @return self
     */
    public function setCampaignSample2($campaign_sample2)
    {
        if (is_null($campaign_sample2)) {
            throw new \InvalidArgumentException('non-nullable campaign_sample2 cannot be null');
        }
        $this->container['campaign_sample2'] = $campaign_sample2;

        return $this;
    }

    /**
     * Gets campaign_sample3
     *
     * @return string|null
     */
    public function getCampaignSample3()
    {
        return $this->container['campaign_sample3'];
    }

    /**
     * Sets campaign_sample3
     *
     * @param string|null $campaign_sample3 campaign_sample3
     *
     * @return self
     */
    public function setCampaignSample3($campaign_sample3)
    {
        if (is_null($campaign_sample3)) {
            throw new \InvalidArgumentException('non-nullable campaign_sample3 cannot be null');
        }
        $this->container['campaign_sample3'] = $campaign_sample3;

        return $this;
    }

    /**
     * Gets campaign_sample4
     *
     * @return string|null
     */
    public function getCampaignSample4()
    {
        return $this->container['campaign_sample4'];
    }

    /**
     * Sets campaign_sample4
     *
     * @param string|null $campaign_sample4 campaign_sample4
     *
     * @return self
     */
    public function setCampaignSample4($campaign_sample4)
    {
        if (is_null($campaign_sample4)) {
            throw new \InvalidArgumentException('non-nullable campaign_sample4 cannot be null');
        }
        $this->container['campaign_sample4'] = $campaign_sample4;

        return $this;
    }

    /**
     * Gets campaign_message_flow
     *
     * @return string|null
     */
    public function getCampaignMessageFlow()
    {
        return $this->container['campaign_message_flow'];
    }

    /**
     * Sets campaign_message_flow
     *
     * @param string|null $campaign_message_flow campaign_message_flow
     *
     * @return self
     */
    public function setCampaignMessageFlow($campaign_message_flow)
    {
        if (is_null($campaign_message_flow)) {
            throw new \InvalidArgumentException('non-nullable campaign_message_flow cannot be null');
        }
        $this->container['campaign_message_flow'] = $campaign_message_flow;

        return $this;
    }

    /**
     * Gets campaign_optin_keywords
     *
     * @return string|null
     */
    public function getCampaignOptinKeywords()
    {
        return $this->container['campaign_optin_keywords'];
    }

    /**
     * Sets campaign_optin_keywords
     *
     * @param string|null $campaign_optin_keywords campaign_optin_keywords
     *
     * @return self
     */
    public function setCampaignOptinKeywords($campaign_optin_keywords)
    {
        if (is_null($campaign_optin_keywords)) {
            throw new \InvalidArgumentException('non-nullable campaign_optin_keywords cannot be null');
        }
        $this->container['campaign_optin_keywords'] = $campaign_optin_keywords;

        return $this;
    }

    /**
     * Gets campaign_optin_message
     *
     * @return string|null
     */
    public function getCampaignOptinMessage()
    {
        return $this->container['campaign_optin_message'];
    }

    /**
     * Sets campaign_optin_message
     *
     * @param string|null $campaign_optin_message campaign_optin_message
     *
     * @return self
     */
    public function setCampaignOptinMessage($campaign_optin_message)
    {
        if (is_null($campaign_optin_message)) {
            throw new \InvalidArgumentException('non-nullable campaign_optin_message cannot be null');
        }
        $this->container['campaign_optin_message'] = $campaign_optin_message;

        return $this;
    }

    /**
     * Gets campaign_optout_keywords
     *
     * @return string|null
     */
    public function getCampaignOptoutKeywords()
    {
        return $this->container['campaign_optout_keywords'];
    }

    /**
     * Sets campaign_optout_keywords
     *
     * @param string|null $campaign_optout_keywords campaign_optout_keywords
     *
     * @return self
     */
    public function setCampaignOptoutKeywords($campaign_optout_keywords)
    {
        if (is_null($campaign_optout_keywords)) {
            throw new \InvalidArgumentException('non-nullable campaign_optout_keywords cannot be null');
        }
        $this->container['campaign_optout_keywords'] = $campaign_optout_keywords;

        return $this;
    }

    /**
     * Gets campaign_optout_message
     *
     * @return string|null
     */
    public function getCampaignOptoutMessage()
    {
        return $this->container['campaign_optout_message'];
    }

    /**
     * Sets campaign_optout_message
     *
     * @param string|null $campaign_optout_message campaign_optout_message
     *
     * @return self
     */
    public function setCampaignOptoutMessage($campaign_optout_message)
    {
        if (is_null($campaign_optout_message)) {
            throw new \InvalidArgumentException('non-nullable campaign_optout_message cannot be null');
        }
        $this->container['campaign_optout_message'] = $campaign_optout_message;

        return $this;
    }

    /**
     * Gets campaign_help_keywords
     *
     * @return string|null
     */
    public function getCampaignHelpKeywords()
    {
        return $this->container['campaign_help_keywords'];
    }

    /**
     * Sets campaign_help_keywords
     *
     * @param string|null $campaign_help_keywords campaign_help_keywords
     *
     * @return self
     */
    public function setCampaignHelpKeywords($campaign_help_keywords)
    {
        if (is_null($campaign_help_keywords)) {
            throw new \InvalidArgumentException('non-nullable campaign_help_keywords cannot be null');
        }
        $this->container['campaign_help_keywords'] = $campaign_help_keywords;

        return $this;
    }

    /**
     * Gets campaign_help_message
     *
     * @return string|null
     */
    public function getCampaignHelpMessage()
    {
        return $this->container['campaign_help_message'];
    }

    /**
     * Sets campaign_help_message
     *
     * @param string|null $campaign_help_message campaign_help_message
     *
     * @return self
     */
    public function setCampaignHelpMessage($campaign_help_message)
    {
        if (is_null($campaign_help_message)) {
            throw new \InvalidArgumentException('non-nullable campaign_help_message cannot be null');
        }
        $this->container['campaign_help_message'] = $campaign_help_message;

        return $this;
    }

    /**
     * Gets campaign_embedded_link
     *
     * @return bool|null
     */
    public function getCampaignEmbeddedLink()
    {
        return $this->container['campaign_embedded_link'];
    }

    /**
     * Sets campaign_embedded_link
     *
     * @param bool|null $campaign_embedded_link campaign_embedded_link
     *
     * @return self
     */
    public function setCampaignEmbeddedLink($campaign_embedded_link)
    {
        if (is_null($campaign_embedded_link)) {
            throw new \InvalidArgumentException('non-nullable campaign_embedded_link cannot be null');
        }
        $this->container['campaign_embedded_link'] = $campaign_embedded_link;

        return $this;
    }

    /**
     * Gets campaign_embedded_link_url
     *
     * @return string|null
     */
    public function getCampaignEmbeddedLinkUrl()
    {
        return $this->container['campaign_embedded_link_url'];
    }

    /**
     * Sets campaign_embedded_link_url
     *
     * @param string|null $campaign_embedded_link_url campaign_embedded_link_url
     *
     * @return self
     */
    public function setCampaignEmbeddedLinkUrl($campaign_embedded_link_url)
    {
        if (is_null($campaign_embedded_link_url)) {
            throw new \InvalidArgumentException('non-nullable campaign_embedded_link_url cannot be null');
        }
        $this->container['campaign_embedded_link_url'] = $campaign_embedded_link_url;

        return $this;
    }

    /**
     * Gets campaign_embedded_phone
     *
     * @return bool|null
     */
    public function getCampaignEmbeddedPhone()
    {
        return $this->container['campaign_embedded_phone'];
    }

    /**
     * Sets campaign_embedded_phone
     *
     * @param bool|null $campaign_embedded_phone campaign_embedded_phone
     *
     * @return self
     */
    public function setCampaignEmbeddedPhone($campaign_embedded_phone)
    {
        if (is_null($campaign_embedded_phone)) {
            throw new \InvalidArgumentException('non-nullable campaign_embedded_phone cannot be null');
        }
        $this->container['campaign_embedded_phone'] = $campaign_embedded_phone;

        return $this;
    }

    /**
     * Gets campaign_age_gated
     *
     * @return bool|null
     */
    public function getCampaignAgeGated()
    {
        return $this->container['campaign_age_gated'];
    }

    /**
     * Sets campaign_age_gated
     *
     * @param bool|null $campaign_age_gated campaign_age_gated
     *
     * @return self
     */
    public function setCampaignAgeGated($campaign_age_gated)
    {
        if (is_null($campaign_age_gated)) {
            throw new \InvalidArgumentException('non-nullable campaign_age_gated cannot be null');
        }
        $this->container['campaign_age_gated'] = $campaign_age_gated;

        return $this;
    }

    /**
     * Gets campaign_direct_lending
     *
     * @return bool|null
     */
    public function getCampaignDirectLending()
    {
        return $this->container['campaign_direct_lending'];
    }

    /**
     * Sets campaign_direct_lending
     *
     * @param bool|null $campaign_direct_lending campaign_direct_lending
     *
     * @return self
     */
    public function setCampaignDirectLending($campaign_direct_lending)
    {
        if (is_null($campaign_direct_lending)) {
            throw new \InvalidArgumentException('non-nullable campaign_direct_lending cannot be null');
        }
        $this->container['campaign_direct_lending'] = $campaign_direct_lending;

        return $this;
    }

    /**
     * Gets campaign_privacy_policy_link
     *
     * @return string|null
     */
    public function getCampaignPrivacyPolicyLink()
    {
        return $this->container['campaign_privacy_policy_link'];
    }

    /**
     * Sets campaign_privacy_policy_link
     *
     * @param string|null $campaign_privacy_policy_link campaign_privacy_policy_link
     *
     * @return self
     */
    public function setCampaignPrivacyPolicyLink($campaign_privacy_policy_link)
    {
        if (is_null($campaign_privacy_policy_link)) {
            throw new \InvalidArgumentException('non-nullable campaign_privacy_policy_link cannot be null');
        }
        $this->container['campaign_privacy_policy_link'] = $campaign_privacy_policy_link;

        return $this;
    }

    /**
     * Gets campaign_terms_and_conditions_link
     *
     * @return string|null
     */
    public function getCampaignTermsAndConditionsLink()
    {
        return $this->container['campaign_terms_and_conditions_link'];
    }

    /**
     * Sets campaign_terms_and_conditions_link
     *
     * @param string|null $campaign_terms_and_conditions_link campaign_terms_and_conditions_link
     *
     * @return self
     */
    public function setCampaignTermsAndConditionsLink($campaign_terms_and_conditions_link)
    {
        if (is_null($campaign_terms_and_conditions_link)) {
            throw new \InvalidArgumentException('non-nullable campaign_terms_and_conditions_link cannot be null');
        }
        $this->container['campaign_terms_and_conditions_link'] = $campaign_terms_and_conditions_link;

        return $this;
    }

    /**
     * Gets campaign_usecase
     *
     * @return string|null
     */
    public function getCampaignUsecase()
    {
        return $this->container['campaign_usecase'];
    }

    /**
     * Sets campaign_usecase
     *
     * @param string|null $campaign_usecase campaign_usecase
     *
     * @return self
     */
    public function setCampaignUsecase($campaign_usecase)
    {
        if (is_null($campaign_usecase)) {
            throw new \InvalidArgumentException('non-nullable campaign_usecase cannot be null');
        }
        $this->container['campaign_usecase'] = $campaign_usecase;

        return $this;
    }

    /**
     * Gets campaign_status
     *
     * @return string|null
     */
    public function getCampaignStatus()
    {
        return $this->container['campaign_status'];
    }

    /**
     * Sets campaign_status
     *
     * @param string|null $campaign_status Pingram-side brand registration workflow status. - not_started: no customer submission yet - pending_review: customer submitted; Pingram has not submitted to carriers - in_progress: submitted for carrier review - approved | rejected | info_needed: review outcome
     *
     * @return self
     */
    public function setCampaignStatus($campaign_status)
    {
        if (is_null($campaign_status)) {
            throw new \InvalidArgumentException('non-nullable campaign_status cannot be null');
        }
        $allowedValues = $this->getCampaignStatusAllowableValues();
        if (!in_array($campaign_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'campaign_status', must be one of '%s'",
                    $campaign_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['campaign_status'] = $campaign_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


